name: djangocms mysite test

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  create-project:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        django-version: [
          '3.2', '4.2',
        ]
        django-cms-version: [
          'git+https://github.com/django-cms/django-cms@develop-4#egg=django-cms'
        ]
        python-version: ['3.11']
        os: [
          ubuntu-20.04,
        ]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}

      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create project from template
      run: |
        python -m venv .venv
        source ./.venv/bin/activate
        python -m pip install --upgrade pip
        pip install ${{ matrix.django-cms-version}}
        djangocms mysite --noinput
